export jboss-parent = $(shell pwd)

jboss-install:
	./jbossInstallSH $(jboss-parent)

jboss-start:
	./jbossStartSH $(jboss-parent)

jboss-stop:
	./jbossStopSH $(jboss-parent)


show:
	@echo $(jboss-parent)




#	$(eval LOCATION := $(shell pwd))
#	@echo $(LOCATION)
##@mkdir $$HOME/zzzzzzzzzz
